"""initial_schema

Revision ID: a0357ddad2b7
Revises: 
Create Date: 2026-01-01 17:23:09.421127+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0357ddad2b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_market_index', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('tank_capacity', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('scrape_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scraper_type', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule_type', sa.Enum('DAILY', 'HOURLY', 'INTERVAL', 'CRON', name='scheduletype'), nullable=True),
    sa.Column('schedule_value', sa.String(length=100), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_configs_id'), 'scrape_configs', ['id'], unique=False)
    op.create_index(op.f('ix_scrape_configs_name'), 'scrape_configs', ['name'], unique=True)
    op.create_table('scrape_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('records_scraped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_history_config_id'), 'scrape_history', ['config_id'], unique=False)
    op.create_index(op.f('ix_scrape_history_id'), 'scrape_history', ['id'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_aliases_alias_name'), 'company_aliases', ['alias_name'], unique=True)
    op.create_index(op.f('ix_company_aliases_id'), 'company_aliases', ['id'], unique=False)
    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gallons', sa.Float(), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('temperature_avg', sa.Float(), nullable=True),
    sa.Column('hdd', sa.Float(), nullable=True),
    sa.Column('raw_sensor_value', sa.Float(), nullable=True),
    sa.Column('adjustment_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_usage_date'), 'daily_usage', ['date'], unique=False)
    op.create_index(op.f('ix_daily_usage_id'), 'daily_usage', ['id'], unique=False)
    op.create_index(op.f('ix_daily_usage_location_id'), 'daily_usage', ['location_id'], unique=False)
    op.create_table('oil_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('gallons', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_gallon', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_dates'),
    sa.CheckConstraint('gallons > 0', name='check_gallons_positive'),
    sa.CheckConstraint('price_per_gallon > 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oil_orders_company_id'), 'oil_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_oil_orders_end_date'), 'oil_orders', ['end_date'], unique=False)
    op.create_index(op.f('ix_oil_orders_id'), 'oil_orders', ['id'], unique=False)
    op.create_index(op.f('ix_oil_orders_location_id'), 'oil_orders', ['location_id'], unique=False)
    op.create_index(op.f('ix_oil_orders_start_date'), 'oil_orders', ['start_date'], unique=False)
    op.create_table('oil_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('price_per_gallon', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('town', sa.String(length=255), nullable=True),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oil_prices_company_id'), 'oil_prices', ['company_id'], unique=False)
    op.create_index(op.f('ix_oil_prices_date_reported'), 'oil_prices', ['date_reported'], unique=False)
    op.create_index(op.f('ix_oil_prices_id'), 'oil_prices', ['id'], unique=False)
    op.create_index(op.f('ix_oil_prices_scraped_at'), 'oil_prices', ['scraped_at'], unique=False)
    op.create_table('tank_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('gallons', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('is_fill_event', sa.Boolean(), nullable=True),
    sa.Column('is_post_fill_unstable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tank_readings_id'), 'tank_readings', ['id'], unique=False)
    op.create_index(op.f('ix_tank_readings_location_id'), 'tank_readings', ['location_id'], unique=False)
    op.create_index('ix_tank_readings_location_timestamp', 'tank_readings', ['location_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_tank_readings_timestamp'), 'tank_readings', ['timestamp'], unique=False)
    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('low_temp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('high_temp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'date', name='uq_location_date')
    )
    op.create_index(op.f('ix_temperatures_date'), 'temperatures', ['date'], unique=False)
    op.create_index(op.f('ix_temperatures_id'), 'temperatures', ['id'], unique=False)
    op.create_index(op.f('ix_temperatures_location_id'), 'temperatures', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperatures_location_id'), table_name='temperatures')
    op.drop_index(op.f('ix_temperatures_id'), table_name='temperatures')
    op.drop_index(op.f('ix_temperatures_date'), table_name='temperatures')
    op.drop_table('temperatures')
    op.drop_index(op.f('ix_tank_readings_timestamp'), table_name='tank_readings')
    op.drop_index('ix_tank_readings_location_timestamp', table_name='tank_readings')
    op.drop_index(op.f('ix_tank_readings_location_id'), table_name='tank_readings')
    op.drop_index(op.f('ix_tank_readings_id'), table_name='tank_readings')
    op.drop_table('tank_readings')
    op.drop_index(op.f('ix_oil_prices_scraped_at'), table_name='oil_prices')
    op.drop_index(op.f('ix_oil_prices_id'), table_name='oil_prices')
    op.drop_index(op.f('ix_oil_prices_date_reported'), table_name='oil_prices')
    op.drop_index(op.f('ix_oil_prices_company_id'), table_name='oil_prices')
    op.drop_table('oil_prices')
    op.drop_index(op.f('ix_oil_orders_start_date'), table_name='oil_orders')
    op.drop_index(op.f('ix_oil_orders_location_id'), table_name='oil_orders')
    op.drop_index(op.f('ix_oil_orders_id'), table_name='oil_orders')
    op.drop_index(op.f('ix_oil_orders_end_date'), table_name='oil_orders')
    op.drop_index(op.f('ix_oil_orders_company_id'), table_name='oil_orders')
    op.drop_table('oil_orders')
    op.drop_index(op.f('ix_daily_usage_location_id'), table_name='daily_usage')
    op.drop_index(op.f('ix_daily_usage_id'), table_name='daily_usage')
    op.drop_index(op.f('ix_daily_usage_date'), table_name='daily_usage')
    op.drop_table('daily_usage')
    op.drop_index(op.f('ix_company_aliases_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias_name'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_scrape_history_id'), table_name='scrape_history')
    op.drop_index(op.f('ix_scrape_history_config_id'), table_name='scrape_history')
    op.drop_table('scrape_history')
    op.drop_index(op.f('ix_scrape_configs_name'), table_name='scrape_configs')
    op.drop_index(op.f('ix_scrape_configs_id'), table_name='scrape_configs')
    op.drop_table('scrape_configs')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
